// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import AutosubmitFormController from "./autosubmit_form_controller"
application.register("autosubmit-form", AutosubmitFormController)

import CheckBoxSelectAllController from "./check_box_select_all_controller"
application.register("check-box-select-all", CheckBoxSelectAllController)

import DisableUploadsController from "./disable_uploads_controller"
application.register("disable-uploads", DisableUploadsController)
