// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import AutosubmitFormController from "./autosubmit_form_controller"
application.register("autosubmit-form", AutosubmitFormController)

import CheckBoxSelectAllController from "./check_box_select_all_controller"
application.register("check-box-select-all", CheckBoxSelectAllController)

import HideOnScrollController from "./hide_on_scroll_controller"
application.register("hide-on-scroll", HideOnScrollController)

import ImageViewerController from "./image_viewer_controller"
application.register("image-viewer", ImageViewerController)

import MediaController from "./media_controller"
application.register("media", MediaController)

import PageVisibilityController from "./page_visibility_controller"
application.register("page-visibility", PageVisibilityController)

import PushNotificationsController from "./push_notifications_controller"
application.register("push-notifications", PushNotificationsController)

import PushNotificationStatusController from "./push_notification_status_controller"
application.register("push-notification-status", PushNotificationStatusController)

import SearchBoxController from "./search_box_controller"
application.register("search-box", SearchBoxController)

import SearchBoxSubmitController from "./search_box_submit_controller"
application.register("search-box-submit", SearchBoxSubmitController)

import TrixFormController from "./trix_form_controller"
application.register("trix-form", TrixFormController)
